"""empty message

Revision ID: 0b9bda500690
Revises: 
Create Date: 2022-05-16 21:48:09.746714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b9bda500690'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('films')
    op.drop_table('posters')
    op.drop_table('genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('genre_id', sa.INTEGER(), server_default=sa.text("nextval('genres_genre_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('genre_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('genre_id', name='genres_pkey'),
    sa.UniqueConstraint('genre_name', name='genres_genre_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('posters',
    sa.Column('poster_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('poster_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('poster_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('poster_id', name='posters_pkey')
    )
    op.create_table('films',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('genres_genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('director', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=5000), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poster', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('users_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.CHAR(length=140), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genres_genre_id'], ['genres.genre_id'], name='films_genres_genre_id_fkey'),
    sa.ForeignKeyConstraint(['users_user_id'], ['users.user_id'], name='films_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='films_pkey')
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('psw', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('user_name', name='users_user_name_key')
    )
    # ### end Alembic commands ###
